---
deployment:
  tasks:
    # - sh ~/public_html/vishwjeet-api/deploy1.sh 2>&1
    - export DEPLOYPATH=~/public_html/
    - /bin/cp -R ~/repositories/vishwjeet-api/ $DEPLOYPATH
    - sh ~/public_html/vishwjeet-api/deploy.sh 2>&1
    